version: '3.1'

volumes:
  postgres_data:
  reids_data:


services:
  postgres:
    image: postgres:14.7
    container_name: postgres
    # 5432로 포워딩 할 경우 host os 에 설치된 postgre와 겹칠 수 있으므로 host에 설치된 postgre를 내려야함
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis
    container_name: my-redis-container
    ports:
      - "6379:6379"  # 로컬 포트와 컨테이너 포트 간의 포트 포워딩
    volumes:
      - reids_data:/data  # 데이터 볼륨 바인딩
    command: redis-server --requirepass yourpassword  # Redis에 액세스하기 위한 비밀번호 설정
    restart: always  # 컨테이너 항상 다시 시작